import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { meals } from '../src/data/meals';

const root = join(import.meta.dirname, '..');
const manifestPath = join(root, 'scripts', 'meal_image_manifest.json');
const imageMapPath = join(root, 'src', 'data', 'mealImages.ts');
const previous = JSON.parse(readFileSync(manifestPath, 'utf8')) as Array<{ id: string; title: string }>;
const previousTitles = new Map(previous.map((item) => [item.id, item.title]));

const titleOverrides: Record<string, string> = {
  'wonton-noodles-soup': 'Wonton noodles',
  'penang-hokkien-mee': 'Prawn noodles',
  'chilli-pan-mee': 'Banmian',
  'wat-tan-hor': 'Wat tan hor',
  'cantonese-fried-noodles': 'Cantonese fried noodles',
  'mee-sua-soup': 'Misua',
  'dry-bak-kut-teh': 'Bak kut teh',
  'penang-chee-cheong-fun': 'Chee cheong fun',
  'ipoh-hor-fun': 'Shahe fen',
  'kampar-curry-chicken-bread': 'Curry bread',
  'kam-heong-lala': 'Clams in Asian cuisine',
  'ginger-scallion-fish': 'Ginger scallion fish',
  'putu-mayam': 'Idiyappam',
  'ayam-buah-keluak': 'Ayam buah keluak',
  'nyonya-chap-chye': 'Cap cai',
  'jiu-hu-char': 'Jiu hu char',
  'udang-lemak-nenas': 'Prawn curry',
  'nyonya-otak-otak': 'Otak-otak',
  'pie-tee': 'Kueh pie tee',
  'nyonya-popiah': 'Popiah',
  'nyonya-nasi-ulam': 'Nasi ulam',
  'nyonya-asam-fish': 'Asam pedas',
  'sambal-petai-prawns': 'Sambal',
  'babi-pongteh': 'Pongteh',
  'tomato-crispy-mee': 'Tomato noodles',
  'manok-pansoh': 'Ayam pansuh',
  'midin-belacan': 'Midin',
  'linopot-set': 'Linopot',
  'pinasakan-sada': 'Pinasakan',
  'ngiu-chap': 'Ngiu chap',
  'beaufort-mee': 'Beaufort noodles',
  'dabai-fried-rice': 'Canarium odontophyllum',
  'thai-chicken-rice': 'Khao man gai',
  'moo-ping': 'Mu ping',
  'tom-yum-noodles': 'Tom yum',
  'indonesian-nasi-goreng': 'Nasi goreng',
  'mie-ayam': 'Mie ayam',
  'sate-ayam-indonesia': 'Satay',
  'indonesian-martabak': 'Martabak',
  'ayam-bakar-indonesia': 'Ayam bakar',
  'vietnamese-chicken-rice': 'Cơm gà',
  'grilled-steak': 'Beef steak',
  'big-breakfast': 'Full breakfast',
  'middle-eastern-mixed-grill': 'Mixed grill',
};

const manifest = meals.map((meal) => ({
  id: meal.id,
  title: previousTitles.get(meal.id) ?? titleOverrides[meal.id] ?? meal.name,
  cuisine: meal.cuisine,
}));
writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');

const imageLines = meals.map((meal) => `  '${meal.imageKey}': require('../../assets/meals/${meal.imageKey}.webp'),`);
writeFileSync(
  imageMapPath,
  `// Generated by scripts/sync_meal_assets.ts. Keep image paths static for Metro.\nexport const mealImages: Record<string, number> = {\n${imageLines.join('\n')}\n};\n`,
  'utf8',
);

console.log(`Synced ${meals.length} manifest entries and static image imports.`);
